Bump proc_macro2 to support building on nightly rust
cargo update proc-macro2

Otherwise the error "error[E0635]: unknown feature
`proc_macro_span_shrink`" will display and the build will fail.

Seems to be okay as of nightly 62ebe3a2b 2023-09-08